---
- name: Install EPEL (CentOS)
  yum:
    name: epel-release
    state: present
    update_cache: true
  when: ansible_pkg_mgr == 'yum'
  register: installed
  until: installed|success
  retries: 5
  delay: 30

- name: Install Auxilliary Packages
  action:
    module: "{{ ansible_pkg_mgr }}" 
    name: "{{ item }}"
    update_cache: true
  when: ansible_os_family in nginx_ancillary_packages.keys()
  with_items: nginx_ancillary_packages[ansible_os_family]|default([])
  register: installed
  until: installed|success
  retries: 5
  delay: 30

- name: Install nginx
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: nginx
    state: present
    update_cache: true
  register: installed
  until: installed|success
  retries: 5
  delay: 30
